### ISSUE TITLE
Problem selecting td inside tr

### ISSUE THREAD

**Issue by Mancuerna** [rushter/selectolax#2]
Hello again. I've using `selectolax` for more than a month now and I have not encounter a single problem until today (apart from the `.text()` addition).

I have the following HTML: https://pastebin.com/PzfLaWrp and when I try to select the `td` elements from it I get an empty result (if I select the `div` elements it yields the proper result) Am I missing something? 

Thank you for your time.

**Comment by lexborisov** [comment]
Hi @Mancuerna 

Everything works correctly. Your html tags ```<tr>``` and ```<td>``` not in ```<table>``` tag. Because of this, these tags will be omitted. In other words, they are simply thrown out during the parsing HTML. (try to open this file in some modern browser, and see result)

See specification [in body parsing state](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody) 

```text
A start tag whose tag name is one of: "caption", "col", "colgroup", "frame", "head", "tbody", "td", "tfoot", "th", "thead", "tr"
Parse error. Ignore the token.
```

**Comment by Mancuerna** [comment]
Oh, didn't know that. Thanks for  pointing that out @lexborisov .
