### ISSUE TITLE
Add lexbor as an alternative backend

### ISSUE THREAD

**Issue by rushter** [rushter/selectolax#42]

**Comment by BarryThrill** [comment]
Just wanted to say thank you for the 0.2.14 update :) I'm currently checking the code changed and looks nice! Do you think it is worth to change from css to select() instead? 

Also I know im too fast... but will those new features be added into your documentation? :D 

Once again, Thank you very much for the awesome update!

**Comment by rushter** [comment]
> Do you think it is worth to change from css to select() instead?

It's better to use it only when you need extra features.

> Also I know im too fast... but will those new features be added into your documentation? 

I've added a few examples https://github.com/rushter/selectolax/blob/master/examples/walkthrough.ipynb
The API is also documented: https://selectolax.readthedocs.io/en/latest/parser.html#selector

**Comment by ma1ex** [comment]
@rushter, hi! Is XPath support planned for the future?

**Comment by rushter** [comment]
> @rushter, hi! Is XPath support planned for the future?

I don't think so, because XPath is a pretty complex query language. It's basically a programming language.

If you need some of the features from XPath, let me know.  Some of them can be implemented using the new selector feature.

**Comment by ma1ex** [comment]
> If you need some of the features from XPath, let me know. Some of them can be implemented using the new selector feature.

In new data extraction projects I decided to experimentally try to replace LXML module with your module, because I liked the performance. But it really lacked `contains()` analogue for text and had to do a separate filtering by text in the list of selected items. With `select().text_contains()` it definitely became more convenient, thank you very much!

Is there any way to do selection by the content of a certain text in the attributes? In XPath it looks something like this: `//div[contains(@data-source, "img-big")]` , `//table/tr[not(contains(@class, "title"))]`

And is there an analogue of `normalize-space()` for text nodes (`normalize-space(//div[@class="offers-form"]/div/text())`)? To end up with a single space between words, and to cut off the special line feed characters, tabs, etc. at both ends.

**Comment by rushter** [comment]
> > If you need some of the features from XPath, let me know. Some of them can be implemented using the new selector feature.
> 
> In new data extraction projects I decided to experimentally try to replace LXML module with your module, because I liked the performance. But it really lacked `contains()` analogue for text and had to do a separate filtering by text in the list of selected items. With `select().text_contains()` it definitely became more convenient, thank you very much!
> 
> Is there any way to do selection by the content of a certain text in the attributes? In XPath it looks something like this: `//div[contains(@data-source, "img-big")]` , `//table/tr[not(contains(@class, "title"))]`

Yes, you can do that. `div[data-source*="img-big"]` and `table tr :not(.title)` (not sure about the second one, but you can definitely do that).

> And is there an analogue of `normalize-space()` for text nodes (`normalize-space(//div[@class="offers-form"]/div/text())`)? To end up with a single space between words, and to cut off the special line feed characters, tabs, etc. at both ends.

No

**Comment by ma1ex** [comment]
> Yes, you can do that. `div[data-source*="img-big"]` and `table tr :not(.title)` or `table :not(tr[class*="title"])` (not sure about the correctness of the second one, but you can definitely do that).

Great! Thank you so much!

**Comment by croqaz** [comment]
I know this issue is closed, but maybe it's possible to use something like https://github.com/sissaschool/elementpath
They support the standard ElementTree library and the [lxml.etree](http://lxml.de/). If the API is compatible, it would be easy to add selectolax into elementpath.
